services:
  app:
    build: .

    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

